# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
executors:
  project-executer:
    docker:
      # specify the version you desire here
      - image: circleci/node:11.10.0

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/Angular-Boilerplate

jobs:

  setup-environment:
    executor: project-executor
    steps:
      - checkout
      - run: 
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      
      - run:
          name: Install local dependencies
          command: |
            sudo npm i npm@6.7.0 -g
            npm install
      - run:
          name: Build Node Sass
          command: npm install --unsafe-perm node-sass

      - save_cache:
          key: v1-dependencies-{{checksum "package.json"}}
          paths:
            - node_modules
      
      - persist_to_workspace:
          root: .
          paths: 
            - src
            - package.json
            - angular.json
            - Dockerfile
            - tslint.json
            - tsconfig.json
            - .firebaserc
            - firebase.json
  
build:
  executor: project-executer
  steps:
    - attach_workspace:
        at: ~/Angular-Boilerplate
    # Download and cache dependencies
    - restore_cache:
        keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
    
    - run:
        name: Building
        command: |
          if [[ "${CIRCLE_BRANCH}" == "staging-"* ]]; then
            npm run build-staging
          elif [ "${CIRCLE_BRANCH}" == "master" ]; then
            npm run build
          else
            npm run build
          fi
    # Cache the dist folder for the deploy job
    - save_cache:
        key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
        paths:
          - dist
    - persist_to_workspace:
        root: .
        paths:
          - dist
